### ISSUE TITLE
Can we include the parent id for every glottolog id in the language csv?

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#105]
If parent id was a column in the csv, users could do their own mapping of dialects to iso codes.

E.g.

asan1239 > does not have an iso code in the csv file, or any 'parent' info

- i had to go to glottolog to decide whether to link asan1239 to iso [twi] twii1234 or iso [aka] akan1250.

- and even if we want to totally drop iso codes, having the parent info would allow users to identify relationships among dialects based on a shared parent.

@xrotwang, what do you think?

**Comment by xrotwang** [comment]
I assume with "shared parent" you specifically mean language-level parent, right? If the ISO code mapping is the main use case for including this information, then I'd say we include the "nearest" ISO code directly - not via a Glottolog languoid which has an equivalent ISO code; in particular because the corresponding Glottolog languoid may not be a language, but a dialect or family.

But generally, the mapping between Glottolog and ISO isn't trivial and requires some judgement calls; so going to Glottolog, to inspect the data available to Glottolog to make the judgement more fully, may actually be the proper way to assess the mapping.

**Comment by kirbykat** [comment]
By parent i actually just meant the dialect/language/language family one 'nesting level' above that of the D-PLACE glottolog id, whatever that might be. Overall I would find it useful to have an up-to-date version of the glottolog mapping file available in the repository, so that assignment of some missing ISO codes (or matching of related glottolog langoids, if I'm using that term right) could be automated (rather than having to type each one into the glottolog site). 

But maybe you are arguing this is not a good idea because the user might not realize that iso assignment/determination of relationships among glottolog IDs is not trivial?

**Comment by xrotwang** [comment]
Assignment of ISO codes can be automated as follows: If a Glottolog languoid has no corresponding ISO code, check the direct parent, and repeat if necessary. We can do that, and just hope people know what they are doing, e.g. when they merge data from different sources where one source is identified with ISO codes ...

**Comment by xrotwang** [comment]
Should this be implemented for the data repository, or upon import into the D-PLACE app? Since mapping between ISO and Glottolog isn't completely trivial - see Harald's long paper on the issue - I would say we don't want to appear as providing a variant of this mapping here, but provide it as some sort of device for the "lazy" researcher in the app download.

**Comment by SimonGreenhill** [comment]
I agree, I think this is an app issue.
