### ISSUE TITLE
Some societies are missing links to eHRAF cultures

### ISSUE THREAD

**Issue by kirbykat** [D-PLACE/dplace-data#110]
A user writes: "On an unrelated note, we saw that there are a number of societies in D-PLACE where the corresponding HRAF culture is not noted (for example, Zulu (EA: Ab12; HRAF: FX20), Rwandans (EA: Ae10; HRAF: FO57), Dogon (EA: Ag3; HRAF: FA16), Mentawaians (EA:Ib7; HRAF: OD09), etc.). Is there a reason for this?"

I checked each of these examples and they are all linked in my file -- what's the best way to figure out why they are not linked on the site?

**Comment by xrotwang** [comment]
I only checked for Zulu: The HRAF URL is still there - in the new scheme of things as values in the `HRAF_link` and `HRAF_name_ID` columns of a dataset's `societies.csv` file, e.g.:
https://github.com/D-PLACE/dplace-data/blob/master/datasets/EA/societies.csv
See https://github.com/D-PLACE/dplace-data/blob/master/datasets/README.md for a description of the dataset layout.

In the current D-PLACE app code (which isn't feeding the website yet!) `HRAF_name_ID` is loaded into the database:
https://github.com/D-PLACE/dplace/blob/master/dplace_app/loader/society.py#L69
and should be displayed on a society's details page via:
https://github.com/D-PLACE/dplace/blob/master/dplace_app/templates/society.html#L179-L181

It turns out, though, that (currently) the condition `if xd_id` which wraps the displaying part of code, isn't met (and shouldn't wrap the HRAF link anyway) - so that's a bug. Whether the same bug is also present in the old code, which currently runs the website would require a bit more detective work...

**Comment by kirbykat** [comment]
@xrotwang thanks for looking into this

**Comment by SimonGreenhill** [comment]
@xrotwang  -- can I take this to mean that the bug is fixed when we update to v2? Reopen if not.
