### ISSUE TITLE
EA202 is coded oddly in "EA/codes"

### ISSUE THREAD

**Issue by petyaracz** [D-PLACE/dplace-data#116]
EA202 (pop size) coding is somehow off in "codes.csv" though I'm not sure what's wrong (since I don't entirely understand the coding logic). So if you merge "variables" and "codes" and "data" together, EA202 just drops out.

**Comment by xrotwang** [comment]
EA202 is a bit of a special case (only in the EA dataset, though), in that it is a *continuous* (not really, I know, but non-categorical) rather than a *categorical* variable. For these variables, individual codes are **not** listed in `codes.csv`. Thus, joining `data.csv` and `codes.csv` will result in no matching rows.

**Comment by SimonGreenhill** [comment]
There's not much we can do to fix this, right?
