### ISSUE TITLE
Release as CLDF

### ISSUE THREAD

**Issue by SimonGreenhill** [D-PLACE/dplace-data#252]
It would be nice to release this as CLDF like the rest of our projects. This might need some thinking about how to deal with the different types of data in DPLACE (phylogenies? geo data?)

**Comment by xrotwang** [comment]
Yes, the current D-PLACE data layout was one step in the design process leading to CLDF, so should be somewhat compatible. We'd basically treat societies as languages, but considering that we have datasets with dialects and other varieties, this may not be totally inappropriate.

**Comment by xrotwang** [comment]
Regarding phylogenies, I'd say the simplest thing would be two more CSV files:
- `phylogenies.csv` - basically what's now `phylogenies/index.csv`, but with the actual tree added as column `newick` or similar
- `taxa.csv` with columns `Name,Phylogeny_ID,Glottocode`

**Comment by SimonGreenhill** [comment]
Sounds good -- do we need to have a spec for phylogenies in CLDF? (I can see this being useful for glottolog, for example, and trees are in the grambank release too, right? also for the datasets in lexibank that come with phylogenies, it could be neat to have those incorporated).

Three things to think about:
1. do we actually need taxa.csv and not just an extra column in (`taxon`?) in languages.csv

2. do we want to insist on translated or untranslated trees i.e. translated = `((1,2),3)` vs untranslated =  `((Language1,Language2),Language3)`. Translated is smaller and but harder to use (code would need to be written to fill the taxa labels in from taxa.csv), while the latter is bigger but more transparent. (writing this now, I think untranslated is better).

3. We'd need to handle both the summary (n=1 tree) and posterior trees (n=many). So, we could either have one phylogenies.csv, which would then need another column for a tree label (i.e. tree number and probably `type` e.g.:

```csv
ID,Label,Type,Newick
1,Summary,Maximum Clade Credibility,(...)
2,Posterior10000,Posterior,(...)
3,Posterior11000,Posterior,(...)
4,Posterior12000,Posterior,(...)
5,Posterior13000,Posterior,(...)
```

... or two files.

**Comment by xrotwang** [comment]
I'm not sure the full posterior tree sets are ripe for standardization. E.g. the processing we apply to the "raw" tree sets (sampling) may not be appropriate for all use cases. So I think I'd leave these out for the first step.

I think `taxa.csv` is necessary (or at least useful), because we want to keep the full phylogenies, i.e. including tree tips we don't have in `languages.csv`. Full trees make most sense with the labels of their source context, I'd say. So one layer of translation between `languages.csv` and tree labels is necessary and must be phylogeny-specific.

What I find more problematic for standardizing phylogenies is the D-PLACE quirk of one tree tip corresponding to several societies (which share the same Glottocode). For a standardized phylogeny in a CLDF dataset, I'd hope for more integration, e.g. as it would be the case for the IE Wordlist dataset, complemented with the phylogeny computed from the data, where we'd have one-to-one correspondence between tree tips and `languages.csv`. Maybe `Language_ID` in `taxa.csv` could be list-valued (optionally), and when converting the D-PLACE data we explicitly resolve the society-glottocode mapping?

**Comment by SimonGreenhill** [comment]
Ok, agree with leaving posterior out for now and keeping taxa.csv.

Yes, I agree that a 1-1 mapping would be nicer. THere are tools in R to 'glue in' missing tips, and we could try implement something in python to do this as part of the DPLACE -- it's not too difficult, e.g. 

```
- find the branch with multple tips : tips
- for each tip in shuffle(tips),
    - find branch for the tip that is on tree
    - split this branch-length in two (or either in half or randomly): above, below
    - set tip branch length to "above" (i.e. so it's short and becomes a node)
    - add two child branches to this with length "below" (so they become tips with the same length as all the others).
```

**Comment by xrotwang** [comment]
Hm, I think I'd find list-valued columns in taxa.csv more intuitive. In
particular because I think trees should look the same when used with
different society mappings.
Or maybe regard the phylogenies in d-place as weird special case. Actually
they'd better be part of Glottolog CLDF - where the 1-1 relation would hold
naturally.

Simon J Greenhill <notifications@github.com> schrieb am Fr., 19. Juli 2019,
10:39:

**Comment by xrotwang** [comment]
Releasing the trees with https://github.com/cldf-datasets/dplacetrees will be the first step.

**Comment by SimonGreenhill** [comment]
This is done, right?
